//  Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: reactive-service-testing
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2020-04-13
:page-guide-category: microprofile
:page-essential: false
:page-description: Learn how to use MicroShed Testing to test reactive messaging microservices.
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Jakarta EE', 'Microservices']
:page-related-guides: ['microprofile-reactive-messaging', 'microshed-testing', 'reactive-messaging-sse', 'microprofile-reactive-messaging-acknowledgement', 'microprofile-rest-client-async']
:page-permalink: /guides/{projectid}
:imagesdir: /img/guide/{projectid}
:page-seo-title: Testing MicroProfile Reactive Messaging microservices using MicroShed Testing (MST)
:page-seo-description: A getting started tutorial with examples on how to test asynchronous Java microservices in a MicroProfile Reactive Messaging application using MicroShed Testing (MST).
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/dev
:source-highlighter: prettify
= Testing a reactive messaging microservice using MicroShed Testing.

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to test reactive messaging services using MicroShed Testing.

== What you'll learn

You will start with a reactive messaging service that runs on Open Liberty and learn how to use MicroShed Testing to
write tests that exercise the service inside of a Docker container.

=== What is Microprofile Reactive Messaging?

The MicroProfile Reactive Messaging specification utilizes a message-driven architecture by providing an
easy way to send, receive, and process messages. The application featured in this guide uses the `System` and `Inventory`
services to showcase a reactive messaging architecture. To learn more about Microprofile Reactive Messaging and how
the application works, check out the
https://openliberty.io/guides/microprofile-reactive-messaging.html[Creating asynchronous reactive microservices using MicroProfile Reactive Messaging^]
guide.

=== What is MicroShed Testing?

MicroShed Testing (MST) offers a fast and simple way of writing and running true-to-production integration tests for Java
microservice applications. MicroShed Testing exercises your containerized application from outside the container so you
are testing the exact same image that runs in production. To learn more about MicroShed Testing, check out the
https://openliberty.io/guides/microshed-testing.html[Testing a MicroProfile or Jakarta EE application^] guide.

== Additional prerequisites

You will build, run, and test the services in Docker containers. To learn more about containerizing microservices
with Docker, check out the https://openliberty.io/guides/containerize.html[Containerizing microservices^] guide.

Install Docker by following the instructions on the official
https://docs.docker.com/engine/installation[Docker documentation^]. Start your Docker environment. Ensure you are using
Linux containers, not Windows.

[role='command']
include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished application. Give it a try before you proceed.

To try out the tests, go to the `finish` directory and run the following Maven goal to install the `models`
artifact to the local Maven repository for later use by the `System` and `Inventory` services:

[role='command']
```
mvn -pl models install
```

Now navigate to the `finish/system` directory and run the following Maven goal to build the `System` service and run
the integration tests on an Open Liberty server in a container:

[role='command']
```
mvn verify
```

You will see the following output:

[role='no_copy']
```
 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 33.001 s - in it.io.openliberty.guides.system.SystemServiceIT

 Results:

 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0


 --- maven-failsafe-plugin:2.22.2:verify (verify) @ system ---
 ------------------------------------------------------------------------
 BUILD SUCCESS
 ------------------------------------------------------------------------
 Total time:  52.817 s
 Finished at: 2020-03-13T16:28:55-04:00
 ------------------------------------------------------------------------
```

This command might take some time to run the first time because the dependencies and the Docker image for Open Liberty
must download. If you run the same command again, it will be faster.

Similarly, you can try out the `Inventory` integration tests by repeating the same commands in the `finish/inventory`
directory.

== Creating the System service tests

//File 0
system/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/system/pom.xml[]
----

//File 1
system/AppContainerConfig.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/system/src/test/java/it/io/openliberty/guides/system/AppContainerConfig.java[]
----

//File 2
SystemServiceIT.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/system/src/test/java/it/io/openliberty/guides/system/SystemServiceIT.java[]
----

//File 3
SystemLoad.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/models/src/main/java/io/openliberty/guides/models/SystemLoad.java[]
----

//File 4
SystemService.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/system/src/main/java/io/openliberty/guides/system/SystemService.java[]
----

=== Configuring your containers

Navigate to the `start` directory to begin.

The provided example reactive application consists of the `System` and `Inventory` microservices, which produces to and
consumes messages from Kafka respectively. You will write integration tests to see how you can use the Kafka consumer
and producer client APIs to test each service. MST and Kafka test containers have already been included as required
test dependencies in your Maven project `system/` and `inventory/` [hotspot=dependencies file=0]`pom.xml` files.

Run the following Maven goal to install the `models` artifact to the local Maven repository for later use by the
`System` and `Inventory` services:

[role='command']
```
mvn -pl models install
```

With Open Liberty development mode, you can use MicroShed Testing to run tests on an already running Open Liberty server.
Navigate to the `start/system` directory.

[role='command']
include::{common-includes}/devmode-start.adoc[]

Now you can add your test files.


[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `AppContainerConfig` class.#
`system/src/test/java/it/io/openliberty/guides/system/AppContainerConfig.java`
----


The [hotspot=AppContainerConfig file=1]`AppContainerConfig` class externalizes test container set up and configuration, so you can use
the same application containers across multiple tests. The [hotspot=container, container2 file=1]`@Container` annotation denotes an
application container that will be started up and used in the tests.

There are two containers that will be used for testing the `System` service. First is the [hotspot=kafka file=1]`kafka` container
that the `System` service will be producing messages to. Second is the [hotspot=system file=1]`system` container,
which uses the same container that you built.

The [hotspot=dependsOn file=1]`dependsOn()` annotation specifies that the `system` service container should wait until the `kafka`
container is ready before starting up.

=== Testing your containers

Now you can start writing your test that will use the configured containers.


[role="code_command hotspot file=2", subs="quotes"]
----
#Create the `SystemServiceIT` class.#
`system/src/test/java/it/io/openliberty/guides/system/SystemServiceIT.java`
----


The test uses the [hotspot=KafkaConsumer, KafkaConsumer2 file=2]`KafkaConsumer` client API, and
is configured using the [hotspot=KafkaConsumerConfig file=2]`@KafkaConsumerConfig` annotation. The consumer client is configured
to consume messages from the [hotspot=systemLoadTopic file=2]`systemLoadTopic` topic from the `kafka` container.
To learn more about Kafka APIs and how to use them, check out the
https://kafka.apache.org/documentation/#api[official Kafka Documentation^]

To consume messages from a stream, they will need to be deserialized from bytes. Kafka has its own default deserializer,
however, a customer deserializer has been provided for you, and is configured to the consumers's
[hotspot=valueDeserializer file=2]`valueDeserializer` and has been implemented in the
[hotspot=SystemLoadDeserializer file=3]`SystemLoad` class.

The running `System` service container will produce messages to the [hotspot=systemLoad file=4]`systemLoad` Kafka topic,
as denoted by the [hotspot=Outgoing file=4]`@Outgoing` annotation. The [hotspot=testCpuStatus file=2]`testCpuStatus()`
test method will [hotspot=poll file=2]`poll()` records from Kafka over 30 seconds.
It will then [hotspot=assert file=2]`verify` that the record polled matched the expected record.

[role='command']
include::{common-includes}/devmode-test.adoc[]

You will see the following output:

[role='no_copy']
```
 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.674 s - in it.io.openliberty.guides.system.SystemServiceIT

 Results:

 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

 Integration tests finished.
```

After you are finished running tests, stop the Open Liberty server by typing `q` in the shell session where you ran
the server, and then press the `enter/return` key.

You can also run the tests via a cold start by running the following command:

[role='command']
```
mvn verify
```

You will see the following output:

[role='no_copy']
```
 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 33.001 s - in it.io.openliberty.guides.system.SystemServiceIT

 Results:

 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0


 --- maven-failsafe-plugin:2.22.2:verify (verify) @ system ---
 ------------------------------------------------------------------------
 BUILD SUCCESS
 ------------------------------------------------------------------------
 Total time:  52.817 s
 Finished at: 2020-03-13T16:28:55-04:00
 ------------------------------------------------------------------------
```

== Creating the Inventory service tests

//File 0
InventoryServiceIT.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryServiceIT.java[]
----

//File 1
SystemLoad.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/models/src/main/java/io/openliberty/guides/models/SystemLoad.java[]
----

The `Inventory` service can be tested the same way as the `System` service, the only difference being that the `Inventory`
service consumes messages, allowing tests to be written using the Kafka producer client.

=== Configuring your containers

The `AppContainerConfig` class has been provided for you, and is configured in the same way as the `System` service.
The two containers configured for use in the `Inventory` service integration test is the `Kafka` and `Inventory`
containers.

=== Testing your containers


[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `InventoryServiceIT` class.#
`inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryServiceIT.java`
----

The [hotspot=InventoryServiceIT file=0]`InventoryServiceIT` class utilizes the [hotspot=KafkaProducer, KafkaProducer file=0]`KafkaProducer`
client to produce messages in the test environment for the `Inventory` service container to consume. The producer is
configured using the [hotspot=KafkaProducerConfig file=0]`@KafkaProducerConfig` annotation to use the custom serializer provided
in the [hotspot=JsonbSerializer file=1]`SystemLoad` class. The config annotation does not include a topic for the client
to produce messages to, as it has the flexibility to produce messages to any topic, and is shown producing messages to
the [hotspot=systemLoadTopic file=0]`systemLoadTopic` topic.

The [hotspot=testCpuUsage file=0]`testCpuUsage` test method will produce a message to Kafka, and then
[hotspot=assert, assert2, assert3 file=0]`verify` that the response from the `Inventory` service matches what is expected.

[role='command']
include::{common-includes}/devmode-test.adoc[]

You will see the following output:

[role='no_copy']
```
 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 32.564 s - in it.io.openliberty.guides.inventory.InventoryServiceIT

 Results:

 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

 Integration tests finished.
```

After you are finished running tests, stop the Open Liberty server by typing `q` in the shell session where you ran
the server, and then press the `enter/return` key.

You can also run the tests via a cold start by running the following command:

[role='command']
```
mvn verify
```

You will see the following output:

[role='no_copy']
```
 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 42.345 s - in it.io.openliberty.guides.inventory.InventoryServiceIT

 Results:

 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0


 --- maven-failsafe-plugin:2.22.2:verify (verify) @ inventory ---
 ------------------------------------------------------------------------
 BUILD SUCCESS
 ------------------------------------------------------------------------
 Total time:  48.213 s
 Finished at: 2020-03-13T16:43:34-04:00
 ------------------------------------------------------------------------
```

== Great work! You're done!

You have just tested two reactive messaging services using MicroShed Testing.

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]

Learn more about MicroShed Testing.

https://microshed.org/microshed-testing/[Visit the official MicroShed Testing website^]

include::{common-includes}/attribution.adoc[subs="attributes"]
