//  Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: reactive-service-testing
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2020-04-13
:page-guide-category: microprofile
:page-essential: false
:page-description: Learn how to use MicroShed Testing to test reactive message microservices.
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Jakarta EE', 'Microservices'
:page-related-guides: ['microprofile-reactive-messaging'
:page-permalink: /guides/{projectid}
:imagesdir: /img/guide/{projectid}
:page-seo-title: Testing a MicroProfile Reactive Messaging microservice
:page-seo-description: A tutorial on how to test reactive messaging microservices.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/dev
:source-highlighter: prettify
= Testing a reactive messaging microservice using MicroShed Testing.

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to test reactive messaging services using MicroShed Testing.

== What you'll learn

You will start with a reactive messaging service that runs on Open Liberty and use MicroShed Testing to write tests
that exercise the service inside of a Docker container.

=== What is Microprofile Reactive Messaging?

The MicroProfile Reactive Messaging specification utilizes a message-driven architecture by providing an
easy way to send, receive, and process messages. The application featured in this guide uses the `OpenLibertyCafe`
application that mimics a cafe. To learn more about Microprofile Reactive Messaging and how the application works, check out the
https://openliberty.io/guides/microprofile-reactive-messaging.html[Creating asynchronous reactive microservices using MicroProfile Reactive Messaging^]
guide.

=== What is MicroShed Testing?

MicroShed Testing (MST) offers a fast and simple way of writing and running true-to-production integration tests for Java
microservice applications. MicroShed Testing exercises your containerized application from outside the container so you
are testing the exact same image that runs in production. To learn more about MicroShed Testing, check out the
https://openliberty.io/guides/microshed-testing.html[Testing a MicroProfile or Jakarta EE application^] guide.

== Additional prerequisites

You will build, run, and test the service in a Docker container. To learn more about containerizing microservices
with Docker, check out the https://openliberty.io/guides/containerize.html[Containerizing microservices^] guide.

Install Docker by following the instructions on the official
https://docs.docker.com/engine/installation[Docker documentation^]. Start your Docker environment.

[role='command']
include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished application. Give it a try before you proceed.

To try out the tests, go to the `finish` directory and run the following Maven goal to install the `models`
artifact to the local Maven repository for later use by the `kitchen` and other services:

[role='command']
```
mvn -pl models install
```

Now navigate to the `finish/kitchen` directory and run the following Maven goal to build the `kitchen` service and run
the integration tests on an Open Liberty server in a container:

[role='command']
```
mvn verify
```

You will see the following output:

[role='no_copy']
```
 Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 33.001 s - in it.io.openliberty.guides.kitchen.KitchenServiceIT

 Results:

 Tests run: 2, Failures: 0, Errors: 0, Skipped: 0


 --- maven-failsafe-plugin:2.22.2:verify (verify) @ kitchen ---
 ------------------------------------------------------------------------
 BUILD SUCCESS
 ------------------------------------------------------------------------
 Total time:  37.817 s
 Finished at: 2020-03-13T16:28:55-04:00
 ------------------------------------------------------------------------
```

This command might take some time to run the first time because the dependencies and the Docker image for Open Liberty
must download. If you run the same command again, it will be faster.

== Creating the tests

//File 0
kitchen/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/kitchen/pom.xml[]
----

//File 1
AppContainerConfig.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/kitchen/src/test/java/it/io/openliberty/guides/kitchen/AppContainerConfig.java[]
----

//File 2
KitchenServiceIT.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/kitchen/src/test/java/it/io/openliberty/guides/kitchen/KitchenServiceIT.java[]
----

//File 3
Order.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/models/src/main/java/io/openliberty/guides/models/Order.java[]
----

//File 4
KitchenService.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/kitchen/src/main/java/io/openliberty/guides/kitchen/KitchenService.java[]
----

=== Configuring your containers

Navigate to the `start` directory to begin.

The `OpenLibertyCafe` reactive application consists of multiple microservices. You will focus on the `kitchen` microservice for this guide.
MST and Kafka test containers have already been included as required test dependencies in your Maven project
[hotspot=dependencies file=0]`pom.xml` file.

Run the following Maven goal to install the `models` artifact to the local Maven repository for later use by the
`kitchen` and other services:

[role='command']
```
mvn -pl models install
```

With Open Liberty development mode, you can use MicroShed Testing to run tests on an already running Open Liberty server.
Run the following Maven goal to start Open Liberty in development mode:

[role='command']
```
mvn liberty:dev
```

Now Open Liberty is listening for file changes and updates in real time. Now you can add your test files.


[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `AppContainerConfig` class.#
`kitchen/src/test/java/it/io/openliberty/guides/kitchen/AppContainerConfig.java`
----


The [hotspot file=1]`AppContainerConfig` class externalizes test container set up and configuration, so you can use
the same application containers across multiple tests.

There are two containers that will be used for testing the `kitchen` service. First is the [hotspot=kafka file=1]`kafka` container
that the `kitchen` service will be producing and consuming messages from. Second is the [hotspot=kitchen file=1]`kitchen` container,
which uses the same container that you built instead of a mimic test container.

The [hotspot=dependsOn file=1]`dependsOn()` annotation specifies that the `kitchen` service container should wait until the `kafka`
container is ready before starting up.

=== Testing your containers

Now you can start writing your tests that will use the configured containers.


[role="code_command hotspot file=2", subs="quotes"]
----
#Create the `KitchenServiceIT` class.#
`kitchen/src/test/java/it/io/openliberty/guides/kitchen/KitchenServiceIT.java`
----


The tests use the Kafka client APIs `KafkaProducer` and `KafkaConsumer` to communicate with the `kafka` container, and
is configured using the [hotspot=KafkaProducerConfig file=2]`@KafkaProducerConfig` and
[hotspot=KafkaConsumerConfig file=2]`@KafkaConsumerConfig` annotations. The consumer client is configured
to subscribe and consume messages from the [hotspot=statusTopic file=2]`statusTopic` topic. The producer can
produce messages to any topic and is shown producing an Order message to the [hotspot=foodTopic file=2]`foodTopic` topic.

To transmit messages to a stream, they will need to be serialized into bytes. Kafka has its own default serializer,
however a customer serializer has been provided for you, and configured to the producer's
[hotspot=KafkaProducerConfig file=2]`valueSerializer`. The custom serializer is implemented in the
[hotspot=JsonbSerializer file=3]`Order` class. Similarly, a deserializer has been configured to the consumer's
[hotspot=valueDeserializer file=2]`valueDeserializer` and has been implemented in the
[hotspot=OrderDeserializer file=3]`Order` class.

The [hotspot=testInProgress file=2]`testInProgress` test will be executed first, and will produce a message to the
[hotspot=foodTopic file=2]`foodTopic` topic. The `kitchen` service will consume that message from the `foodOrderConsume`
stream, as denoted by the [hotspot=Incoming file=4]`@Incoming` annotation on the
[hotspot=receiveFoodOrder file=4]`receiveFoodOrder()` method. The
[hotspot=receiveFoodOrder file=4]`receiveFoodOrder()` method will publish back an `IN_PROGRESS` message to the
`foodOrderPublishStatus` stream as denoted by the [hotspot=Outgoing file=4]`@Outgoing` annotation.

The [hotspot=verify file=2]`verify()` method will [hotspot=poll file=2]`poll()` records from Kafka over 30 seconds.
It will then [hotspot=assert file=2]`verify` that the record polled matched the expected record. For example, the first
[hotspot=verifyInProgress file=2]`verify()` method call expects that the first `Order` record polled to have a status of
[hotspot=verifyInProgress file=2]`IN_PROGRESS`, and also ensures that the `Order` record has the right `orderId`.

== Running the tests

Open Liberty development mode automatically recompiles and updated your test code changes. To run the tests, press the
`enter/return` key. You will see the following output:

[role='no_copy']
```
 Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.674 s - in it.io.openliberty.guides.kitchen.KitchenServiceIT

 Results:

 Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

 Integration tests finished.
```

After you are finished running tests, stop the Open Liberty server by typing `q` in the shell session where you ran
the server, and then press the `enter/return` key.

You can also run the tests via a cold start by running the following command:

[role='command']
```
mvn verify
```

You will see the following output:

[role='no_copy']
```
 Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 33.001 s - in it.io.openliberty.guides.kitchen.KitchenServiceIT

 Results:

 Tests run: 2, Failures: 0, Errors: 0, Skipped: 0


 --- maven-failsafe-plugin:2.22.2:verify (verify) @ kitchen ---
 ------------------------------------------------------------------------
 BUILD SUCCESS
 ------------------------------------------------------------------------
 Total time:  37.817 s
 Finished at: 2020-03-13T16:28:55-04:00
 ------------------------------------------------------------------------
```

All of the other microservices in the application contain similar tests, feel free to try them out with the same commands
in their respective directories.

== Great work! You're done!

You have just tested a reactive messaging service using MicroShed Testing.

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]

Learn more about MicroShed Testing.

https://microshed.org/microshed-testing/[Visit the official MicroShed Testing website^]

include::{common-includes}/attribution.adoc[subs="attributes"]
